name: Test Photo Organizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y exiftool imagemagick
    
    - name: Create test images and set up test environment
      run: |
        # Create necessary directories
        mkdir -p test_images/{complete_exif,partial_exif,no_exif}
        mkdir -p test_scripts/test_cases/{exif_test,camera_test,combined_test}/input
        
        # Make scripts executable
        chmod +x test_images/create_test_images.sh
        chmod +x test_scripts/setup_test_images.sh
        
        # Run the image creation script
        cd test_images
        ./create_test_images.sh
        
        # Copy test images directly to test directories
        cp -r complete_exif/* ../test_scripts/test_cases/exif_test/input/
        cp -r partial_exif/* ../test_scripts/test_cases/exif_test/input/
        cp -r no_exif/* ../test_scripts/test_cases/exif_test/input/
        
        cp -r complete_exif/* ../test_scripts/test_cases/camera_test/input/
        cp -r partial_exif/* ../test_scripts/test_cases/camera_test/input/
        cp -r no_exif/* ../test_scripts/test_cases/camera_test/input/
        
        cp -r complete_exif/* ../test_scripts/test_cases/combined_test/input/
        cp -r partial_exif/* ../test_scripts/test_cases/combined_test/input/
        cp -r no_exif/* ../test_scripts/test_cases/combined_test/input/
    
    - name: Run all tests
      run: |
        cd test_scripts
        # Make all test scripts executable
        chmod +x run_all_tests.sh
        chmod +x test_single.sh
        chmod +x test_cases/*/*.sh
        ./run_all_tests.sh